name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build 
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/service2 .
        
      - name: Test
        run: echo "Test passed"
        
      - name: Push
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/service2
      
